version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  target-branch: master
  assignees:
  - qmenoret
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
    - 14.14.24
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: "@babel/register"
    versions:
    - 7.12.13
    - 7.13.0
    - 7.13.14
    - 7.13.8
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/node"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.16
    - 7.12.17
